[build]
builder = "DOCKERFILE"
dockerfilePath = "BACKEND/Dockerfile"

[deploy]
healthcheckPath = "/api/categorias"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

